/**
 * Generated by PluginGenerator 0.14.0 from webgme on Sat Mar 05 2016 14:54:03 GMT-0600 (Central Standard Time).
 */

define([], function () {
    'use strict';
    return {
        'Client': '/3/d',
        'Component': '/3/8',
        'Component Instance': '/3/F',
        'Container': '/3/j',
        'Deployment': '/3/i',
        'Deployment Workspace': '/3/W',
        'FCO': '/1',
        'Hardware': '/3/U',
        'Hardware Workspace': '/3/K',
        'Host': '/3/m',
        'Interface': '/3/x',
        'Link': '/3/f',
        'Message': '/3/I',
        'Network': '/3/b',
        'Node': '/3/L',
        'Package': '/3/5',
        'Port': '/3/z',
        'Project': '/3/h',
        'Publisher': '/3/2',
        'ROSMOD_META': '/3',
        'Server': '/3/q',
        'Service': '/3/Z',
        'Software Workspace': '/3/R',
        'Subscriber': '/3/c',
        'Timer': '/3/l',
        'User': '/3/s',
    };
});