/**
 * Generated by PluginGenerator 0.14.0 from webgme on Thu Mar 24 2016 11:05:37 GMT-0700 (PDT).
 */

define([], function () {
    'use strict';
    return {
        'Client': '/3/d',
        'Component': '/3/8',
        'Component Instance': '/3/F',
        'Container': '/3/j',
        'Deployment': '/3/i',
        'Deployments': '/3/W',
        'Documentation': '/3/n',
        'Experiment': '/3/9',
        'Experiments': '/3/r',
        'FCO': '/1',
        'Host': '/3/m',
        'Interface': '/3/x',
        'Library': '/3/1',
        'Link': '/3/f',
        'Message': '/3/I',
        'Network': '/3/b',
        'Node': '/3/L',
        'Package': '/3/5',
        'Port': '/3/z',
        'Project': '/3/h',
        'Publisher': '/3/2',
        'Results': '/3/P',
        'ROSMOD_META': '/3',
        'Server': '/3/q',
        'Service': '/3/Z',
        'Software': '/3/R',
        'Source Library': '/3/V',
        'Subscriber': '/3/c',
        'System': '/3/U',
        'System Library': '/3/w',
        'Systems': '/3/K',
        'Timer': '/3/l',
        'User': '/3/s',
    };
});